export const FETCH_LAST_20_MESSAGES = "FETCH_LAST_20_MESSAGES";
export const ADD_LAST_20_MESSAGES = "ADD_LAST_20_MESSAGES";
export const ADD_10_PREVIOUS_MESSAGES = "ADD_10_PREVIOUS_MESSAGES";
export const SEND_MESSAGE = "SEND_MESSAGE";
export const ADD_NEW_MESSAGES = "ADD_NEW_MESSAGES";

export const SET_FRIEND_ID = 'SET_FRIEND_ID';
export const ADD_ERROR = "ADD_ERROR";


export const START_FETCHING_20_LAST_MESSAGES = "START_FETCHING_20_LAST_MESSAGES";
export const STOP_FETCHING_20_LAST_MESSAGES = 'STOP_FETCHING_20_LAST_MESSAGES';
export const START_FETCHING_10_PREVIOUS_MESSAGES = 'START_FETCHING_10_PREVIOUS_MESSAGES';
export const STOP_FETCHING_10_PREVIOUS_MESSAGES = "STOP_FETCHING_10_PREVIOUS_MESSAGES";